import { callAI } from './aiClient.js';

const ANALYZABLE_EXTENSIONS = new Set([
  'js', 'jsx', 'ts', 'tsx', 'py', 'java', 'go', 'rs', 'rb', 'php',
  'c', 'cpp', 'h', 'hpp', 'cs', 'swift', 'kt', 'scala', 'r', 'lua',
  'vue', 'svelte', 'dart', 'ex', 'exs', 'hs', 'ml', 'clj', 'sh',
  'sql', 'graphql', 'proto', 'tf', 'yaml', 'yml', 'toml', 'json',
]);

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '.next', '__pycache__',
  'vendor', '.venv', 'venv', 'target', '.gradle', 'bin', 'obj',
  'coverage', '.nyc_output', '.turbo', '.cache', 'public/static',
]);

const BOILERPLATE_PATTERNS = [
  /^create-react-app/i, /^npx create/i, /^vue create/i,
  /^Generated by|^Auto-generated|^This file was generated/i,
  /^import.*from ['"]@nestjs/, /^import.*from ['"]next\//,
];

export class AnalyzerService {
  constructor(githubService) {
    this.github = githubService;
  }

  async analyzeRepo(owner, repo, branch = 'main') {
    const [repoInfo, readme, languages, commits, issues, prs] = await Promise.all([
      this.github.getRepo(owner, repo),
      this.github.getReadme(owner, repo),
      this.github.getLanguages(owner, repo),
      this.github.listCommits(owner, repo, { sha: branch }),
      this.github.listIssues(owner, repo),
      this.github.listPullRequests(owner, repo),
    ]);

    const tree = await this.github.getTree(owner, repo, repoInfo.default_branch);
    const codeFiles = this.filterCodeFiles(tree);
    const sampledFiles = this.sampleFiles(codeFiles, 10);
    const fileContents = await this.fetchFileContents(owner, repo, sampledFiles, branch);
    console.log(`[Analyzer] Fetched ${fileContents.length} files, total chars: ${fileContents.reduce((s, f) => s + f.content.length, 0)}`);

    const commitAnalysis = this.analyzeCommits(commits, repoInfo.owner.login);

    const analysisPrompt = this.buildAnalysisPrompt({
      repoInfo,
      readme,
      languages,
      fileContents,
      commitAnalysis,
    });

    console.log(`[Analyzer] Calling AI for ${owner}/${repo}...`);
    const text = await callAI([{ role: 'user', content: analysisPrompt }], { maxTokens: 4096 });
    console.log(`[Analyzer] AI response received (${text.length} chars)`);

    const result = this.parseAnalysisResult(text);
    return {
      tech_stack: result.tech_stack,
      architecture: result.architecture,
      core_logic: result.core_logic,
      personal_contributions: result.personal_contributions,
      commit_summary: commitAnalysis.summary,
      readme_summary: readme ? readme.substring(0, 500) : null,
    };
  }

  filterCodeFiles(tree) {
    return tree.filter(item => {
      if (item.type !== 'blob') return false;
      const parts = item.path.split('/');
      if (parts.some(p => SKIP_DIRS.has(p))) return false;
      const ext = item.path.split('.').pop()?.toLowerCase();
      return ext && ANALYZABLE_EXTENSIONS.has(ext);
    });
  }

  sampleFiles(files, maxCount) {
    if (files.length <= maxCount) return files;

    const byExt = {};
    for (const f of files) {
      const ext = f.path.split('.').pop().toLowerCase();
      if (!byExt[ext]) byExt[ext] = [];
      byExt[ext].push(f);
    }

    const sampled = [];
    const exts = Object.keys(byExt).sort((a, b) => byExt[b].length - byExt[a].length);
    const perExt = Math.max(2, Math.floor(maxCount / exts.length));

    for (const ext of exts) {
      const group = byExt[ext];
      const count = Math.min(perExt, group.length);
      const step = Math.max(1, Math.floor(group.length / count));
      for (let i = 0; i < group.length && sampled.length < maxCount; i += step) {
        sampled.push(group[i]);
      }
    }
    return sampled.slice(0, maxCount);
  }

  async fetchFileContents(owner, repo, files, branch) {
    const results = [];
    for (const file of files) {
      const content = await this.github.getFileContent(owner, repo, file.path);
      if (content) {
        const isBoilerplate = BOILERPLATE_PATTERNS.some(p => p.test(content.substring(0, 500)));
        results.push({
          path: file.path,
          content: content.substring(0, 3000),
          isBoilerplate,
        });
      }
    }
    return results;
  }

  analyzeCommits(commits, ownerLogin) {
    const personal = commits.filter(c =>
      c.committer?.login === ownerLogin || c.author?.login === ownerLogin
    );

    const categories = { features: [], fixes: [], refactors: [], other: [] };
    for (const c of personal) {
      const msg = c.commit?.message?.toLowerCase() || '';
      if (msg.match(/^(add|feat|feature|implement|new|create)/)) categories.features.push(c.commit.message.split('\n')[0]);
      else if (msg.match(/^(fix|bug|hotfix|patch|resolve)/)) categories.fixes.push(c.commit.message.split('\n')[0]);
      else if (msg.match(/^(refactor|clean|optimize|perf|improve)/)) categories.refactors.push(c.commit.message.split('\n')[0]);
      else categories.other.push(c.commit.message.split('\n')[0]);
    }

    return {
      totalCommits: commits.length,
      personalCommits: personal.length,
      categories,
      summary: `${personal.length}/${commits.length} commits by owner. ` +
        `Features: ${categories.features.length}, Fixes: ${categories.fixes.length}, Refactors: ${categories.refactors.length}`,
    };
  }

  buildAnalysisPrompt({ repoInfo, readme, languages, fileContents, commitAnalysis }) {
    return `【重要】请全部使用简体中文回答。所有文本内容必须是中文。

你是一位资深技术招聘官和软件架构师。分析这个 GitHub 仓库并产出结构化分析。

## 仓库信息
- 名称: ${repoInfo.full_name}
- 描述: ${repoInfo.description || '无'}
- 语言: ${repoInfo.language || '无'}
- Stars: ${repoInfo.stargazers_count}
- 语言分布: ${JSON.stringify(languages)}

## README（摘录）
${readme?.substring(0, 1500) || '无 README'}

## 提交分析
${commitAnalysis.summary}
重要提交:
${commitAnalysis.categories.features.slice(0, 5).map(c => `- [功能] ${c}`).join('\n')}
${commitAnalysis.categories.fixes.slice(0, 3).map(c => `- [修复] ${c}`).join('\n')}
${commitAnalysis.categories.refactors.slice(0, 3).map(c => `- [重构] ${c}`).join('\n')}

## 代码样本（部分可能是样板代码 —— 请仔细区分）
${fileContents.map(f => `\n### ${f.path} ${f.isBoilerplate ? '（可能是样板代码）' : ''}\n\`\`\`\n${f.content.substring(0, 800)}\n\`\`\``).join('\n')}

用 JSON 格式回答：
{
  "tech_stack": ["实际使用的技术、框架、库的列表"],
  "architecture": "系统架构和设计模式的2-3句话描述",
  "core_logic": "核心业务逻辑和技术实现的2-3句话描述",
  "personal_contributions": ["从代码和提交中可识别的具体技术成就列表，排除样板代码"]
}`;
  }

  parseAnalysisResult(text) {
    try {
      const match = text.match(/\{[\s\S]*\}/);
      if (match) return JSON.parse(match[0]);
    } catch {}
    return {
      tech_stack: [],
      architecture: text.substring(0, 200),
      core_logic: text.substring(0, 200),
      personal_contributions: [],
    };
  }

  detectSignificantChanges(oldAnalysis, newAnalysis) {
    const oldTech = new Set(JSON.parse(oldAnalysis.tech_stack || '[]'));
    const newTech = JSON.parse(newAnalysis.tech_stack || '[]');
    const newTechStack = newTech.filter(t => !oldTech.has(t));

    const oldContribs = JSON.parse(oldAnalysis.personal_contributions || '[]');
    const newContribs = JSON.parse(newAnalysis.personal_contributions || '[]');
    const oldContribSet = new Set(oldContribs);
    const newContributions = newContribs.filter(c => !oldContribSet.has(c));

    const oldArch = (oldAnalysis.architecture || '').toLowerCase();
    const newArch = (newAnalysis.architecture || '').toLowerCase();
    const archChanged = oldArch && newArch && oldArch !== newArch;

    const hasChanges = newTechStack.length > 0 || newContributions.length > 0 || archChanged;
    const changeSummary = [
      newTechStack.length > 0 ? `New technologies: ${newTechStack.join(', ')}` : '',
      newContributions.length > 0 ? `New contributions: ${newContributions.length}` : '',
      archChanged ? 'Architecture evolved' : '',
    ].filter(Boolean).join('. ');

    return { hasChanges, changeSummary, newTechStack, newContributions };
  }
}
